'use strict';
const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
const endpoint='https://n8n.orbbotia.com/webhook/meia-pizza-admin';
const segmento=params.get('segmento')||'restaurante';
let dados=null, atual=null, ocupada=false, contaCarregada='',chaveCarregada='';
const moeda=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const op=(value,text)=>{const n=el('option',text);n.value=value;return n;};
function select(list,value){const n=el('select');list.forEach(([v,t])=>n.append(op(v,t)));if(value!==undefined)n.value=value;return n;}
function aviso(text,erro=false){$('aviso').className='notice '+(erro?'error':'success');$('aviso').textContent=text;}
const mensagens={acesso_negado:'Chave inválida para este estabelecimento.',versao_divergente:'Esta configuração foi alterada em outra sessão. Recarregue o cadastro e revise antes de salvar.',sabores_insuficientes:'A configuração exige mais sabores distintos ativos do que os que estão vinculados. Adicione outro produto de pizza ativo nessa categoria ou reduza o mínimo.',produto_precisa_estar_em_categoria_de_pizza_ativa:'Esse produto não está ativo em uma categoria de pizza disponível. Confira a categoria e o cadastro do produto.',sabores_precisam_ser_da_mesma_categoria:'Todos os sabores da mesma configuração precisam vir da categoria de pizza escolhida.',vinculo_indisponivel:'Um produto ou tamanho deixou de existir ou está inativo. Recarregue o cadastro e refaça esse vínculo.',cadastro_invalido_ou_indisponivel:'Não foi possível salvar. Confira se cada sabor usa um produto diferente, se os tamanhos ainda estão ativos e se as regras estão preenchidas.',configuracao_invalida:'Revise os limites, a divisão e os dados desta configuração.',configuracao_incompleta:'Preencha todos os campos obrigatórios e vínculos antes de salvar.',grupo_obrigatorio_impossivel:'Uma personalização obrigatória não pode ser atendida pelos sabores escolhidos. Confira o vínculo do grupo aos produtos em Personalizações.',conta_sem_catalogo:'Este estabelecimento ainda não possui produtos cadastrados.',limite_sabores:'Confira o mínimo e máximo de sabores.',sabor_repetido:'Escolha sabores diferentes.',fracoes_invalidas:'As partes devem somar 100%, em incrementos de 5%.',grupo_obrigatorio_sem_regra:'Um sabor possui uma escolha obrigatória sem regra nesta montagem.',limite_grupo:'As quantidades não atendem aos limites de uma escolha.',opcao_indisponivel_ou_limite:'Uma opção não está disponível em todos os sabores necessários ou excede o limite.',composicao_indisponivel:'Ative e salve a configuração antes de simular.',catalogo_desatualizado:'O cadastro de tamanhos precisa ser reconciliado antes da prévia.'};
async function request(acao,body={},versao=null){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
 try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','x-pizza-admin-key':chaveCarregada},body:JSON.stringify({account_id:contaCarregada,segmento,acao,dados:body,versao_esperada:versao}),signal:controller.signal});
 let result;try{result=await r.json();}catch{throw Error('O serviço não retornou uma resposta válida. Confira se o novo fluxo está publicado.');}
 if(!r.ok||result.status==='erro'||result.status==='pendencia')throw Error(mensagens[result.codigo]||result.mensagem||result.codigo||'Falha na operação.');return result;
 }finally{clearTimeout(timer);}
}
async function executar(fn){if(ocupada)return;ocupada=true;$('area').disabled=true;$('carregar').disabled=true;try{await fn();}catch(e){aviso(e.name==='AbortError'?'O serviço demorou para responder. Recarregue e confira antes de repetir a gravação.':e.message,true);}finally{ocupada=false;$('area').disabled=!dados;$('carregar').disabled=false;}}
const produtos=()=>dados.catalogo.produtos.filter(p=>p.ativo&&!p.deletado);
const variacoesProduto=id=>dados.catalogo.produto_variacoes.filter(v=>v.produto_id===id&&v.ativo);
const produtosElegiveis=()=>produtos().filter(p=>/pizza/i.test(p.categoria||'')&&p.categoria_id&&variacoesProduto(p.id).length>0&&p.metadata?.esgotado!==true&&p.metadata?.status_estoque!=='esgotado');
const categoriasPizza=()=>{const map=new Map();for(const p of produtosElegiveis()){const id=p.categoria_id;if(!map.has(id))map.set(id,{id,nome:p.categoria,produtos:new Set()});map.get(id).produtos.add(p.id);}return [...map.values()].map(c=>({...c,quantidade:c.produtos.size})).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));};
const categoriaSelecionada=()=> $('categoria-sabores').value;
const produtosDaCategoria=()=>produtosElegiveis().filter(p=>p.categoria_id===categoriaSelecionada());
function atualizarStatusSabores(){const count=produtosDaCategoria().length,min=Number($('minimo').value||2);$('sabores-status').className='notice '+(count>=min?'success':'error');$('sabores-status').textContent=count?`Categoria ${categoriasPizza().find(c=>c.id===categoriaSelecionada())?.nome||'Pizza'}: ${count} sabor${count===1?'':'es'} distinto${count===1?'':'s'} ${count===1?'disponível':'disponíveis'}. Para ativar esta configuração com mínimo ${min}, vincule ao menos ${min} produtos diferentes.`:'Não há sabores disponíveis nessa categoria. Ative ou cadastre produtos de pizza com tamanhos ativos.';}
function atualizarCategorias(valor=''){const s=$('categoria-sabores');s.replaceChildren(op('','Escolha a categoria'));for(const c of categoriasPizza())s.append(op(c.id,`${c.nome} · ${c.quantidade===1?'1 sabor disponível':`${c.quantidade} sabores disponíveis`}`));if(valor&&categoriasPizza().some(c=>c.id===valor))s.value=valor;else if(categoriasPizza().length===1)s.value=categoriasPizza()[0].id;}
function lista(){
 $('lista').replaceChildren();
 for(const c of dados.configuracoes){const d=el('details');d.append(el('summary',`${c.nome} — ${c.tamanho} · ${c.ativo?'Ativa':'Rascunho'}`));const categoria=c.categoria_id?dados.catalogo.produtos.find(p=>p.categoria_id===c.categoria_id)?.categoria:'Categoria ainda não definida';const nomes=c.sabores.map(s=>dados.catalogo.produtos.find(p=>p.id===s.produto_id)?.nome||'Produto indisponível');d.append(el('p',`Categoria: ${categoria||'Pizza'} · ${c.minimo} a ${c.maximo} sabores · ${c.sabores.length} vínculos salvos · ${ {maior:'maior preço',media:'média simples',proporcional:'preço proporcional'}[c.formula] }`));d.append(el('p',nomes.length?`Sabores: ${nomes.join(', ')}`:'Nenhum sabor vinculado.'));
 const row=el('div');row.className='row';const editar=el('button','Editar');editar.className='secondary';editar.onclick=()=>formulario(c);const excluir=el('button','Excluir');excluir.className='danger';excluir.onclick=()=>{if(confirm(`Excluir ${c.nome} — ${c.tamanho}? Os produtos e adicionais serão preservados.`))executar(async()=>{dados=await request('excluir',{id:c.id},c.versao);lista();formulario();aviso('Configuração excluída.');});};row.append(editar,excluir);d.append(row);$('lista').append(d);}
 if(!dados.configuracoes.length)$('lista').append(el('p','Nenhuma configuração cadastrada. Comece pelas regras abaixo.'));
 $('previa-config').replaceChildren(op('','Selecione'));dados.configuracoes.forEach(c=>$('previa-config').append(op(c.id,`${c.nome} — ${c.tamanho}${c.ativo?'':' (rascunho)'}`)));resetPrevia();
}
function formulario(c=null){atual=c;for(const k of ['nome','tamanho'])$(k).value=c?.[k]||'';for(const [k,v]of Object.entries({formula:'maior',divisao:'iguais',minimo:2,maximo:2}))$(k).value=c?.[k]??v;$('ativo').checked=c?.ativo||false;$('editando').textContent=c?`Editando ${c.nome} — ${c.tamanho}`:'Nova configuração';$('sabores').replaceChildren();$('grupos').replaceChildren();const linkedCategory=c?.categoria_id||dados.catalogo.produtos.find(p=>p.id===c?.sabores?.[0]?.produto_id)?.categoria_id||'';atualizarCategorias(linkedCategory);(c?.sabores||[]).forEach(s=>sabor(s));(c?.grupos||[]).forEach(g=>grupo(g));atualizarStatusSabores();}
function sabor(s={}){const row=el('div');row.className='entry';const inputs=el('div');inputs.className='row';const p=select([['','Escolha o produto'],...produtosDaCategoria().map(p=>[p.id,p.nome])],s.produto_id),v=select([]);p.dataset.tipo='produto';v.dataset.tipo='variacao';p.setAttribute('aria-label','Produto do sabor');v.setAttribute('aria-label','Tamanho do sabor');
 const atualizar=()=>{v.replaceChildren(op('','Escolha o tamanho'));variacoesProduto(p.value).forEach(x=>v.append(op(x.id,`${x.nome} · ${moeda(Number(x.preco)*100)}`)));};p.onchange=atualizar;atualizar();if(s.variacao_id)v.value=s.variacao_id;const remove=el('button','Remover vínculo');remove.className='danger';remove.onclick=()=>{row.remove();atualizarStatusSabores();};inputs.append(p,v,remove);row.append(inputs);$('sabores').append(row);}
function grupo(g={}){const row=el('div');row.className='entry';const r=el('div');r.className='row';const id=select([['','Escolha o grupo'],...dados.catalogo.personalizacao_grupos.filter(g=>g.ativo).map(g=>[g.id,g.nome])],g.grupo_id),escopo=select([['inteira','Pizza inteira'],['parte','Por parte/sabor']],g.escopo||'inteira'),cobranca=select([]);id.dataset.tipo='grupo';escopo.dataset.tipo='escopo';cobranca.dataset.tipo='cobranca';id.setAttribute('aria-label','Grupo');escopo.setAttribute('aria-label','Aplicar em');cobranca.setAttribute('aria-label','Regra de cobrança');
 const atualizar=()=>{cobranca.replaceChildren();(escopo.value==='inteira'?[['maior','Maior preço entre sabores'],['media','Média simples entre sabores'],['proporcional','Proporcional às partes']]:[['integral','Preço integral da opção por parte'],['proporcional','Preço proporcional à parte']]).forEach(x=>cobranca.append(op(...x)));};escopo.onchange=atualizar;atualizar();if(g.cobranca)cobranca.value=g.cobranca;const remove=el('button','Remover regra');remove.className='danger';remove.onclick=()=>row.remove();r.append(id,escopo,cobranca,remove);row.append(r,el('small','Preço específico do tamanho prevalece sobre o padrão da opção. Ex.: adicional de R$6 em meia pizza custa R$6 no integral ou R$3 no proporcional.'));$('grupos').append(row);}
const configPrevia=()=>dados?.configuracoes.find(c=>c.id===$('previa-config').value);
function escolhas(container,regras){container.replaceChildren();for(const r of regras){const g=dados.catalogo.personalizacao_grupos.find(g=>g.id===r.grupo_id);if(!g)continue;const d=el('details');d.append(el('summary',`${g.nome} · ${r.cobranca}`));dados.catalogo.personalizacao_opcoes.filter(o=>o.grupo_id===g.id&&o.ativo).forEach(o=>{const label=el('label',o.nome),q=el('input');q.type='number';q.min=0;q.max=o.max_quantidade;q.value=0;q.dataset.grupo=g.id;q.dataset.opcao=o.id;label.append(q);d.append(label);});container.append(d);}}
function parte(){const c=configPrevia();if(!c)return;const row=el('div');row.className='entry';const sel=select([['','Selecione um sabor'],...c.sabores.map(s=>[s.produto_id,dados.catalogo.produtos.find(p=>p.id===s.produto_id)?.nome||'Produto indisponível'])]);sel.dataset.tipo='parte';sel.setAttribute('aria-label','Sabor da parte');const label=el('label',c.divisao==='iguais'?'Partes iguais (divisão automática)':'Percentual desta parte'),peso=el('input');peso.type='number';peso.min=5;peso.max=95;peso.step=5;peso.value=50;peso.hidden=c.divisao==='iguais';peso.dataset.tipo='peso';label.append(peso);const opts=el('div');escolhas(opts,c.grupos.filter(g=>g.escopo==='parte'));const remove=el('button','Remover parte');remove.className='danger';remove.onclick=()=>row.remove();row.append(sel,label,opts,remove);$('previa-partes').append(row);}
function resetPrevia(){$('previa-partes').replaceChildren();$('previa-globais').replaceChildren();$('resultado').replaceChildren();const c=configPrevia();if(!c)return;for(let i=0;i<c.minimo;i++)parte();escolhas($('previa-globais'),c.grupos.filter(g=>g.escopo==='inteira'));}
function modificadores(container){return [...container.querySelectorAll('input[data-opcao]')].filter(x=>Number(x.value)!==0).map(x=>({grupo_id:x.dataset.grupo,opcao_id:x.dataset.opcao,quantidade:Number(x.value)}));}
 $('conta').value=params.get('account_id')||'';$('voltar').href='novo.html?'+new URLSearchParams({account_id:$('conta').value,segmento});
$('categoria-sabores').onchange=()=>{for(const row of [...$('sabores').children]){const p=row.querySelector('[data-tipo=produto]');const selected=p.value;if(!produtosDaCategoria().some(item=>item.id===selected)){p.value='';row.querySelector('[data-tipo=variacao]').replaceChildren(op('','Escolha o tamanho'));}p.replaceChildren(op('','Escolha o produto'),...produtosDaCategoria().map(item=>op(item.id,item.nome)));}atualizarStatusSabores();};$('minimo').oninput=atualizarStatusSabores;
$('carregar').onclick=()=>executar(async()=>{dados=null;contaCarregada=$('conta').value.trim();chaveCarregada=$('chave').value.trim();if(!contaCarregada||!chaveCarregada)throw Error('Informe o estabelecimento e a chave.');dados=await request('consultar');lista();formulario();aviso('Cadastro carregado. Você pode criar configurações e testar preços.');});
$('novo').onclick=$('limpar').onclick=()=>formulario();$('add-sabor').onclick=()=>sabor();$('add-grupo').onclick=()=>grupo();$('expandir').onclick=()=>$('lista').querySelectorAll('details').forEach(d=>d.open=true);$('recolher').onclick=()=>$('lista').querySelectorAll('details').forEach(d=>d.open=false);
 $('salvar').onclick=()=>executar(async()=>{const d={id:atual?.id,...Object.fromEntries(['nome','tamanho','formula','divisao'].map(k=>[k,$(k).value.trim()])),minimo:Number($('minimo').value),maximo:Number($('maximo').value),ativo:$('ativo').checked,sabores:[...$('sabores').children].map(r=>({produto_id:r.querySelector('[data-tipo=produto]').value,variacao_id:r.querySelector('[data-tipo=variacao]').value})),grupos:[...$('grupos').children].map(r=>({grupo_id:r.querySelector('[data-tipo=grupo]').value,escopo:r.querySelector('[data-tipo=escopo]').value,cobranca:r.querySelector('[data-tipo=cobranca]').value}))};if(!d.nome||!d.tamanho||!categoriaSelecionada()||d.sabores.some(s=>!s.produto_id||!s.variacao_id)||d.grupos.some(g=>!g.grupo_id))throw Error('Escolha a categoria, preencha nome e tamanho e complete todos os vínculos adicionados.');if(new Set(d.sabores.map(s=>s.produto_id)).size!==d.sabores.length)throw Error('Cada sabor precisa ser um produto diferente. Vários tamanhos da mesma pizza não contam como sabores distintos.');const result=await request('salvar',d,atual?.versao??0);dados=result;lista();formulario(dados.configuracoes.find(c=>c.id===result.id));aviso('Configuração salva. Ela agora aparece na lista acima; use “Editar” para alterá-la depois.');});
$('previa-config').onchange=resetPrevia;$('add-parte').onclick=()=>{if($('previa-partes').children.length>=Number(configPrevia()?.maximo||0))return aviso('Máximo de partes atingido.',true);parte();};
$('simular').onclick=()=>executar(async()=>{$('resultado').replaceChildren();if(!configPrevia())throw Error('Selecione uma configuração salva.');const r=await request('simular',{composicao_id:configPrevia().id,quantidade:Number($('quantidade').value),partes:[...$('previa-partes').children].map(p=>({produto_id:p.querySelector('[data-tipo=parte]').value,percentual:Number(p.querySelector('[data-tipo=peso]').value),modificadores:modificadores(p)})),globais:modificadores($('previa-globais'))});const total=el('p',`${moeda(r.preco_unitario_centavos)} por pizza · ${moeda(r.total_centavos)} total`);total.className='total';$('resultado').append(total,el('p',`Regra: ${{maior:'sabor mais caro',media:'média simples',proporcional:'proporcional às partes'}[r.formula]}.`));r.partes.forEach(p=>$('resultado').append(el('p',`${p.nome} · ${p.variacao} · ${p.fracao.numerador}/${p.fracao.denominador} da pizza · preço inteiro ${moeda(p.preco_base_centavos)}`)));r.modificadores.forEach(m=>$('resultado').append(el('p',`${m.quantidade}× ${m.nome} · ${m.escopo==='inteira'?'pizza inteira':r.partes.find(p=>p.produto_id===m.produto_id)?.nome} · ${m.cobranca}`)));aviso('Prévia calculada. Nenhum pedido foi criado.');});
